function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}function chatTemplate(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {var pug_debug_sources = {"components\u002Fchat\u002Fchat.pug":"div.chat\n    div.chat__header.clearfix \n        span.chat__user-info Войдите в чат через аккаунт Gmail\n        button#sign-in Войти\n        button#sign-out(hidden) Выйти\n    ul.chat__messages\n\n"};
;pug_debug_line = 1;pug_debug_filename = "components\u002Fchat\u002Fchat.pug";
pug_html = pug_html + "\u003Cdiv class=\"chat\"\u003E";
;pug_debug_line = 2;pug_debug_filename = "components\u002Fchat\u002Fchat.pug";
pug_html = pug_html + "\u003Cdiv class=\"chat__header clearfix\"\u003E";
;pug_debug_line = 2;pug_debug_filename = "components\u002Fchat\u002Fchat.pug";
pug_html = pug_html + " ";
;pug_debug_line = 3;pug_debug_filename = "components\u002Fchat\u002Fchat.pug";
pug_html = pug_html + "\u003Cspan class=\"chat__user-info\"\u003E";
;pug_debug_line = 3;pug_debug_filename = "components\u002Fchat\u002Fchat.pug";
pug_html = pug_html + "Войдите в чат через аккаунт Gmail\u003C\u002Fspan\u003E";
;pug_debug_line = 4;pug_debug_filename = "components\u002Fchat\u002Fchat.pug";
pug_html = pug_html + "\u003Cbutton id=\"sign-in\"\u003E";
;pug_debug_line = 4;pug_debug_filename = "components\u002Fchat\u002Fchat.pug";
pug_html = pug_html + "Войти\u003C\u002Fbutton\u003E";
;pug_debug_line = 5;pug_debug_filename = "components\u002Fchat\u002Fchat.pug";
pug_html = pug_html + "\u003Cbutton id=\"sign-out\" hidden=\"hidden\"\u003E";
;pug_debug_line = 5;pug_debug_filename = "components\u002Fchat\u002Fchat.pug";
pug_html = pug_html + "Выйти\u003C\u002Fbutton\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 6;pug_debug_filename = "components\u002Fchat\u002Fchat.pug";
pug_html = pug_html + "\u003Cul class=\"chat__messages\"\u003E\u003C\u002Ful\u003E\u003C\u002Fdiv\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line, pug_debug_sources[pug_debug_filename]);};return pug_html;}